name: Build Aboba IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build IPA
        run: |
          xcodebuild -project Aboba.xcodeproj -scheme Aboba -archivePath Aboba.xcarchive archive
          # Тут магия упаковки в IPA без сертификата (для Feather)
