name: Assemble Aboba IPA
on: [push]
jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create IPA Package
        run: |
          # Собираем все твои труды в один файл
          zip -r Aboba.ipa Payload/
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aboba-VPN-Package
          path: Aboba.ipa
